#!/bin/sh
ak=5KhS09xGoWq6
sk=anwIfUu4QhUEpgFyi09FS9DGFscvn9

bs_host=bcs-sandbox.baidu.com

MULTI_UPLOAD_LEN_LIMIT=256m

openssl_path=/usr/bin/openssl

delete_superfile_temp_file=1

delete_superfile_failed_temp_file=1

delete_fail_log_file=1

get_thread_num=2

get_retry_num=3

put_thread_num=5

put_retry_num=1
